// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FTAnalyzer
{
	public partial class TextPrintView : NSTextView
	{
		public TextPrintView (IntPtr handle) : base (handle)
		{
		}
        
	}
}
