// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using CoreGraphics;

namespace FTAnalyzer.Mac
{
	public partial class FactsWindowController : NSWindowController
	{
		public FactsWindowController (IntPtr handle) : base (handle)
		{
		}
    }
}
