
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Common Practices and Code Improvements", "RECS0064:Warns when a culture-aware 'string.CompareTo' call is used by default", Justification = "<Pending>", Scope = "member", Target = "~M:FTAnalyzer.FactLocation.CompareTo(FTAnalyzer.FactLocation,System.Int32)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Common Practices and Code Improvements", "RECS0060:Warns when a culture-aware 'IndexOf' call is used by default.", Justification = "<Pending>", Scope = "member", Target = "~M:FTAnalyzer.FactLocation.FixNumerics(System.String,System.Boolean)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Common Practices and Code Improvements", "RECS0060:Warns when a culture-aware 'IndexOf' call is used by default.", Justification = "<Pending>", Scope = "member", Target = "~M:FTAnalyzer.FactLocation.FixMultipleSpacesAmpersandsCommas")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Common Practices and Code Improvements", "RECS0062:Warns when a culture-aware 'LastIndexOf' call is used by default.", Justification = "<Pending>", Scope = "member", Target = "~M:FTAnalyzer.FactLocation.#ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Common Practices and Code Improvements", "RECS0063:Warns when a culture-aware 'StartsWith' call is used by default.", Justification = "<Pending>", Scope = "member", Target = "~M:FTAnalyzer.FactLocation.TrimLeadingCommas(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0022:A catch clause that catches System.Exception and has an empty body", Justification = "Crash avoidance", Scope = "member", Target = "~M:FTAnalyzer.FamilyTree.SetRootIndividual(System.Xml.XmlDocument)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0165:Asynchronous methods should return a Task instead of void", Justification = "Contract for caller", Scope = "member", Target = "~M:FTAnalyzer.Mac.AppDelegate.CheckWebVersion")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0022:A catch clause that catches System.Exception and has an empty body", Justification = "<Pending>", Scope = "member", Target = "~M:FTAnalyzer.FamilyTree.GetNotes(System.Xml.XmlNode)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~P:FTAnalyzer.ExportReferrals.ShortCode")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~P:FTAnalyzer.ExportReferrals.FTAnalyzer#IExportReferrals#RelationType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:FTAnalyzer.LostCousinsReferralComparer.Compare(FTAnalyzer.ExportReferrals,FTAnalyzer.ExportReferrals)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:FTAnalyzer.CensusAgeComparer.Compare(FTAnalyzer.CensusIndividual,FTAnalyzer.CensusIndividual)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:FTAnalyzer.Age.#ctor(FTAnalyzer.Individual,FTAnalyzer.FactDate)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:FTAnalyzer.CensusFamily.IsValidIndividual(FTAnalyzer.CensusIndividual,System.Boolean,System.Boolean,System.Boolean)~System.Boolean")]

