// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FTAnalyzer.Mac
{
	public partial class IndividualsViewController : NSViewController
	{
		public IndividualsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
