// This file has been autogenerated from a class added in the UI designer.


using System;
using Foundation;
using FTAnalyzer.Mac.DataSources;
using FTAnalyzer.Utilities;

namespace FTAnalyzer.Mac.ViewControllers
{
    public partial class ColourCensusViewController : BindingListViewController<IDisplayColourCensus>
    {
        public string Country { get; }
        int startColumnIndex;
        int endColumnIndex;

        public ColourCensusViewController(IntPtr handle) : base(string.Empty,string.Empty)
        {
        }

        public ColourCensusViewController (string country) : base(string.Empty, string.Empty)
		{
            Country = country;

            //string defaultProvider = (string)Application.UserAppDataRegistry.GetValue("Default Search Provider");
            //if (defaultProvider == null)
            //    defaultProvider = "FamilySearch";
            //cbCensusSearchProvider.Text = defaultProvider;
            //cbFilter.Text = "All Individuals";
        }

        public override void RefreshDocumentView(SortableBindingList<IDisplayColourCensus> list)
        {
            if (!NSThread.IsMain)
            {
                InvokeOnMainThread(() => RefreshDocumentView(list));
                return;
            }
            CountText = $"Count: {list.Count}";
            UpdateTooltip();

            _tableView.Source = new ColourCensusSource(Country, list);
            _tableView.ReloadData();
            Title = $"Count: {list.Count} records listed.";
        }

        void SetColumns()
        {
            // make all census columns hidden
            //for (int index = GetColumnIndex("C1841"); index <= GetColumnIndex("Ire1911"); index++)
            //    dgReportSheet.Columns[index].Visible = false;

            if (Country.Equals(Countries.UNITED_STATES))
            {
                startColumnIndex = GetColumnIndex("US1790");
                endColumnIndex = GetColumnIndex("US1940");
                // cbFilter.Items[5] = "Outside USA (Dark Grey)";
            }
            else if (Country.Equals(Countries.CANADA))
            {
                startColumnIndex = GetColumnIndex("Can1851");
                endColumnIndex = GetColumnIndex("Can1921");
                // cbFilter.Items[5] = "Outside Canada (Dark Grey)";
            }
            else if (Country.Equals(Countries.IRELAND))
            {
                startColumnIndex = GetColumnIndex("Ire1901");
                endColumnIndex = GetColumnIndex("Ire1911");
                // cbFilter.Items[5] = "Outside Ireland (Dark Grey)";
            }
            else
            {
                startColumnIndex = GetColumnIndex("C1841");
                endColumnIndex = GetColumnIndex("C1939");
                // cbFilter.Items[5] = "Outside UK (Dark Grey)";
            }
            //// show those columns that should be visible for the country in use
            //for (int index = startColumnIndex; index <= endColumnIndex; index++)
            //dgReportSheet.Columns[index].Visible = true;
        }

    }
}
