// This file has been autogenerated from a class added in the UI designer.


using Foundation;
using FTAnalyzer.Mac.ViewControllers;
using FTAnalyzer.Utilities;
using System.Collections.Generic;
using System.Linq;
using FTAnalyzer.Mac.DataSources;

namespace FTAnalyzer.Mac
{
    public partial class FactsViewController<T> : BindingListViewController<T>
	{
        SortableBindingList<IDisplayFact> facts;

        public FactsViewController (string title, Individual individual) : base (title)
		{
            facts = new SortableBindingList<IDisplayFact>();
            AddIndividualsFacts(individual);
            RefreshDocumentView(facts);
		}

        public void RefreshDocumentView(SortableBindingList<IDisplayFact> list)
        {
            if (!NSThread.IsMain)
            {
                InvokeOnMainThread(() => RefreshDocumentView(list));
                return;
            }

            var source = new BindingListTableSource<IDisplayFact>(list);
            _tableView.Source = source;
            _tableView.ReloadData();
        }


        void AddIndividualsFacts(Individual individual)
        {
            IEnumerable<Fact> list = individual.AllFacts.Union(individual.ErrorFacts.Where(f => f.FactErrorLevel != Fact.FactError.WARNINGALLOW));
            foreach (Fact f in list)
                facts.Add(new DisplayFact(individual, f));
        }
    }
}
