// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FTAnalyzer.Mac
{
    public partial class IndividualsController : NSViewController, INSTableViewDataSource, INSTabViewDelegate 
	{
        FamilyTree _familyTree;
        NSTableView _individualsTableView;

		public IndividualsController (IntPtr handle) : base (handle)
		{
            _familyTree = FamilyTree.Instance;
		}

        public int GetRowCount()
        {
            return _familyTree.IndividualCount;
        }
	}
}
