// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using FTAnalyzer.Mac.DataSources;

namespace FTAnalyzer.Mac
{
    public partial class IndividualsViewController : NSViewController
    {
        FamilyTree _familyTree;
        NSTableView _individualsTableView;

        public IndividualsViewController(IntPtr handle) : base(handle)
        {
            _familyTree = FamilyTree.Instance;
        }

        public void ResetDocument()
        {
            if (!NSThread.IsMain)
            {
                InvokeOnMainThread(() => ResetDocument());
                return;
            }

            _individualsTableView = IndividualsTableView;
            _individualsTableView.Source = new IndividualsTableSource();
        }

    }
}
