// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using FTAnalyzer.Mac.DataSources;

namespace FTAnalyzer.Mac
{
    public partial class IndividualsController : NSViewController
	{
        FamilyTree _familyTree;
        NSTableView _individualsTableView;

		public IndividualsController (IntPtr handle) : base (handle)
		{
            _familyTree = FamilyTree.Instance;
    	}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            _individualsTableView = IndividualsTableView;
            _individualsTableView.Source = new IndividualsTableSource();
        }
	}
}
