// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using FTAnalyzer.Mac.DataSources;
using System.Reflection;

namespace FTAnalyzer.Mac
{
    public partial class IndividualsViewController : NSViewController
    {
        FamilyTree _familyTree;
        NSTableView _individualsTableView;

        public IndividualsViewController(IntPtr handle) : base(handle)
        {
            _familyTree = FamilyTree.Instance;
        }

        public void ResetDocument()
        {
            if (!NSThread.IsMain)
            {
                InvokeOnMainThread(() => ResetDocument());
                return;
            }

            _individualsTableView = new NSTableView()
            {
                RowSizeStyle = NSTableViewRowSizeStyle.Default,
                Enabled = true,
                UsesAlternatingRowBackgroundColors = true,
                ColumnAutoresizingStyle = NSTableViewColumnAutoresizingStyle.Sequential
            };

            PropertyInfo[] properties = typeof(IDisplayIndividual).GetProperties();
            foreach (PropertyInfo property in properties)
            {
                var tableColumn = new NSTableColumn()
                {
                    Width = 100,
                    Editable = false,
                    Hidden = false,
                    Title = property.Name
                };
                _individualsTableView.AddColumn(tableColumn);
            }
            _individualsTableView.Source = new IndividualsTableSource();
        }

        public override void LoadView()
        {
            base.LoadView();
            ResetDocument();
            View = _individualsTableView;
        }
    }
}
