// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FTAnalyzer.Mac
{
	public partial class ProgressViewController : NSViewController
	{
		public ProgressViewController (IntPtr handle) : base (handle)
		{
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            ProgressText.StringValue = "empty text";
            ProgressBar.DoubleValue = 0;
        }
    }
}
