// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FTAnalyzer.Mac
{
	public partial class ProgressController : NSWindowController
	{
        public NSViewController Presentor { get; set; }
        ProgressViewController viewController;

		public ProgressController (IntPtr handle) : base (handle)
		{
 		}

        public override void WindowDidLoad()
        {
            base.WindowDidLoad();
            viewController = ContentViewController as ProgressViewController;
        }

        public string ProgressText
        {
            get => viewController.ProgressText.StringValue;
            set => viewController.ProgressText.StringValue = value;
        }

        public NSProgressIndicator ProgressBar => viewController.ProgressBar;

    }
}
