// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FTAnalyzer.Storyboards
{
	public partial class AccessoryViewController : NSViewController
	{
        readonly string[] observedProperties = { "Refresh" };

        public AccessoryViewController (IntPtr handle) : base (handle)
		{
		}

        public NSSet KeyPathsForValuesAffectingPreview() => null;
    }
}
