// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FTAnalyzer.Storyboards
{
	public partial class FTAnalyzerTabViewController : NSTabViewController
	{
		public FTAnalyzerTabViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
