// This file has been autogenerated from a class added in the UI designer.

namespace FTAnalyzer.Storyboards
{
    public partial class TreeTopsViewController : NSViewController
    {
        public TreeTopsViewController(IntPtr handle) : base(handle)
        {
        }
    }
}
