// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using Foundation;
using FTAnalyzer.Utilities;

namespace FTAnalyzer.ViewControllers
{
    public partial class CensusViewController : BindingListViewController<IDisplayCensus>
	{
        BindingListViewController<IDisplayCensus> _individualsViewController;
        AppDelegate App => (AppDelegate)NSApplication.SharedApplication.Delegate;

        public CensusViewController (IntPtr handle) : base (string.Empty, string.Empty)
		{
            _individualsViewController = new BindingListViewController<IDisplayCensus>("Census", "Double click to show a list of facts for the selected individual.");
        }

        public void LoadCensusIndividuals(SortableBindingList<IDisplayCensus> list)
        {
            if (!NSThread.IsMain)
            {
                InvokeOnMainThread(() => LoadCensusIndividuals(list));
                return;
            }
            _individualsViewController.RefreshDocumentView(list);
            SortIndividuals();
        }

        public void SortIndividuals()
        {
            NSSortDescriptor[] descriptors =
            {
                new NSSortDescriptor("Surname", true),
                new NSSortDescriptor("Forename", true)
            };
            _individualsViewController.Sort(descriptors);
        }
    }
}
