// This file has been autogenerated from a class added in the UI designer.


using System;
using AppKit;
using Foundation;
using FTAnalyzer.DataSources;
using FTAnalyzer.Utilities;

namespace FTAnalyzer.ViewControllers
{
    public partial class ColourCensusViewController : BindingListViewController<IDisplayColourCensus>
    {
        public string Country { get; }
        int startColumnIndex;
        int endColumnIndex;
        string CensusProvider { get; }
        int CensusProviderIndex { get; }

        public ColourCensusViewController(IntPtr handle) : base(string.Empty, string.Empty)
        {
        }

        public ColourCensusViewController(string country) : base(string.Empty, string.Empty)
        {
            Country = country;
            CensusProvider = "Find My Past";
            CensusProviderIndex = 1;
            SetColumns();
            //string defaultProvider = (string)Application.UserAppDataRegistry.GetValue("Default Search Provider");
            //if (defaultProvider == null)
            //    defaultProvider = "FamilySearch";
            //cbCensusSearchProvider.Text = defaultProvider;
            //cbFilter.Text = "All Individuals";
        }

        public override void RefreshDocumentView(SortableBindingList<IDisplayColourCensus> list)
        {
            if (!NSThread.IsMain)
            {
                InvokeOnMainThread(() => RefreshDocumentView(list));
                return;
            }
            CountText = $"Count: {list.Count}";
            UpdateTooltip();

            _tableView.Source = new ColourCensusSource(Country, startColumnIndex, endColumnIndex, CensusProvider, list);
            _tableView.ReloadData();
            _printView.Source = _tableView.Source;
            _printView.ReloadData();
            Title = $"Census Research Suggestions {list.Count} records listed.";
        }

        void SetColumns()
        {
            // make all census columns hidden
            for (int index = GetColumnIndex("C1841"); index <= GetColumnIndex("V1925"); index++)
            {
                NSTableColumn column = _tableView.TableColumns().GetValue(index) as NSTableColumn;
                column.Hidden = true;
            }

            if (Country.Equals(Countries.UNITED_STATES))
            {
                startColumnIndex = GetColumnIndex("US1790");
                endColumnIndex = GetColumnIndex("US1940");
                // cbFilter.Items[5] = "Outside USA (Dark Grey)";
            }
            else if (Country.Equals(Countries.CANADA))
            {
                startColumnIndex = GetColumnIndex("Can1851");
                endColumnIndex = GetColumnIndex("Can1921");
                // cbFilter.Items[5] = "Outside Canada (Dark Grey)";
            }
            else if (Country.Equals(Countries.IRELAND))
            {
                startColumnIndex = GetColumnIndex("Ire1901");
                endColumnIndex = GetColumnIndex("Ire1911");
                // cbFilter.Items[5] = "Outside Ireland (Dark Grey)";
            }
            else
            {
                startColumnIndex = GetColumnIndex("C1841");
                endColumnIndex = GetColumnIndex("C1939");
                // cbFilter.Items[5] = "Outside UK (Dark Grey)";
            }
            //// show those columns that should be visible for the country in use
            for (int index = startColumnIndex; index <= endColumnIndex; index++)
            {
                NSTableColumn column = _tableView.TableColumns().GetValue(index) as NSTableColumn;
                column.Hidden = false;
            }
        }

        [Export("ViewDetailsSelector")]
        public override void ViewDetailsSelector()
        {
            if (!NSThread.IsMain)
            {
                InvokeOnMainThread(ViewDetailsSelector);
                return;
            }
            nint row = _tableView.ClickedRow;
            int columnIndex = (int)_tableView.ClickedColumn;
            if (row >= 0 && columnIndex >= startColumnIndex && columnIndex <= endColumnIndex)
            {
                var source = _tableView.Source as ColourCensusSource;
                IDisplayColourCensus person = source.GetRowObject(row) as IDisplayColourCensus;
                int censusYear;
                if (Country == Countries.UNITED_STATES)
                    censusYear = 1790 + (columnIndex - startColumnIndex) * 10;
                else if (Country == Countries.CANADA)
                    censusYear = columnIndex <= GetColumnIndex("Can1901")
                        ? 1851 + (columnIndex - startColumnIndex) * 10
                        : 1901 + (columnIndex - GetColumnIndex("Can1901")) * 5;
                else if (Country.Equals(Countries.IRELAND))
                    censusYear = 1901 + (columnIndex - startColumnIndex) * 10;
                else
                    censusYear = columnIndex == GetColumnIndex("1939") ? 1939 : 1841 + (columnIndex - startColumnIndex) * 10;
                string censusCountry = person.BestLocation(new FactDate(censusYear.ToString())).CensusCountry;
                if (censusYear == 1939 && CensusProvider != "Find My Past" && CensusProvider != "Ancestry")
                    UIHelpers.ShowMessage($"Unable to search the 1939 National Register on {CensusProvider}.", "FTAnalyzer");
                else
                {
                    try
                    {
                        var ft = FamilyTree.Instance;
                        ft.SearchCensus(censusCountry, censusYear, ft.GetIndividual(person.IndividualID), CensusProviderIndex);
                    }
                    catch (CensusSearchException ex)
                    {
                        UIHelpers.ShowMessage(ex.Message);
                    }
                }
            }
        }
    }
}
