// This file has been autogenerated from a class added in the UI designer.
namespace FTAnalyzer.ViewControllers
{
    public partial class FactsWindowViewController : NSTabViewController
    {
        public FactsWindowViewController(IntPtr handle) : base(handle)
        {
        }
    }
}
