// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FTAnalyzer.ViewControllers
{
	public partial class FactsWindowViewController : NSTabViewController
	{
		public FactsWindowViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
