// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FTAnalyzer.ViewControllers
{
	public partial class LCVerifyViewController : NSViewController
	{
		public LCVerifyViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
