// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using FTAnalyzer.Properties;

namespace FTAnalyzer.ViewControllers
{
    public partial class PreferencesViewController : NSViewController
    {
        public PreferencesViewController (IntPtr handle) : base (handle) { }
    
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            switch (Title)
            {
                case "File Handling Preferences":
                    LoadWithFiltersOutlet.Activated += LoadWithFiltersOutlet_Activated;
                    RetryFailedLinesOutlet.Activated += RetryFailedLinesOutlet_Activated;
                    SetFileHandlingSettings();
                    break;
                case "General Preferences":
                    SetGeneralSettings();
                    break;
                case "Non Gedcom Date Preferences":
                    SetNonGedcomDateSettings();
                    break;
            }
        }

        void LoadWithFiltersOutlet_Activated(object sender, EventArgs e)
        {
            FileHandling.Default.LoadWithFilters = LoadWithFiltersOutlet.State == NSCellStateValue.On;
            FileHandling.Default.Save();
            GeneralSettings.Default.ReloadRequired = true;
        }

        void RetryFailedLinesOutlet_Activated(object sender, EventArgs e)
        {
            FileHandling.Default.RetryFailedLines = RetryFailedLinesOutlet.State == NSCellStateValue.On;
            FileHandling.Default.Save();
            GeneralSettings.Default.ReloadRequired = true;
        }

        void SetFileHandlingSettings()
        {
            LoadWithFiltersOutlet.State = FileHandling.Default.LoadWithFilters ? NSCellStateValue.On : NSCellStateValue.Off;
            RetryFailedLinesOutlet.State = FileHandling.Default.RetryFailedLines ? NSCellStateValue.On : NSCellStateValue.Off;
        }

        void SetGeneralSettings()
        {
            // set checkboxes according to loaded settings
        }

        void SetNonGedcomDateSettings()
        {
            // set checkboxes according to loaded settings
        }
    }
}
