// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Collections.Generic;
using FTAnalyzer.Utilities;

namespace FTAnalyzer.ViewControllers
{
    public partial class ResearchViewController : NSViewController
    {
        AppDelegate App => (AppDelegate)NSApplication.SharedApplication.Delegate;

        public ResearchViewController (IntPtr handle) : base (handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            SetButtonsActive(App.Document != null);
        }

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();
            SetButtonsActive(App.Document != null);
        }

        void SetButtonsActive(bool active)
        {
            UKColourCensus.Enabled = active;
            IrishColourCensus.Enabled = active;
            USColourCensus.Enabled = active;
            CanadianColourCensus.Enabled = active;
        }

        partial void UKCensusClicked(NSObject sender)
        {
            DisplayColourCensus(Countries.UNITED_KINGDOM, sender);
        }

        partial void IrishCensusClicked(NSObject sender)
        {
            DisplayColourCensus(Countries.IRELAND, sender);
        }

        partial void USCensusClicked(NSObject sender)
        {
            DisplayColourCensus(Countries.UNITED_STATES, sender);
        }

        partial void CanadianCensusClicked(NSObject sender)
        {
            DisplayColourCensus(Countries.CANADA, sender);
        }

        void DisplayColourCensus(string country, NSObject sender)
        {
            Console.WriteLine(sender);
            var storyboard = NSStoryboard.FromName("ColourCensus", null);
            var ColourCensusWindow = storyboard.InstantiateControllerWithIdentifier("ColourCensusWindow") as NSWindowController;
            RelationTypes relationTypes = new RelationTypes();
            List<IDisplayColourCensus> list = FamilyTree.Instance.ColourCensus(country, relationTypes, string.Empty, null, false, false);
            ColourCensusViewController colourCensusViewController = new ColourCensusViewController(country);
            colourCensusViewController.RefreshDocumentView(new SortableBindingList<IDisplayColourCensus>(list));
            ColourCensusWindow.ContentViewController.AddChildViewController(colourCensusViewController);
            ColourCensusWindow.Window.Title = colourCensusViewController.Title;
            ColourCensusWindow.Window.SetFrame(new CoreGraphics.CGRect(350, 350, 1000, 475), true);
            ColourCensusWindow.ShowWindow(this);

            Analytics.TrackAction(Analytics.MainFormAction, Analytics.ColourCensusEvent);
        }
    }
}
